<p>This section contains an example of LightningPacker using its PHP library</p>

<p>The <a target="_blank" href="/html/example-with-lp.phtml">example-with-lp.phtml</a> contains an example using LightningPacker.</p>

<p>The page <a target="_blank" href="/html/example-without-lp.phtml">example-without-lp.phtml</a> is the very same page but instead of call LightningPacker the page is calling each script separately</p>

<p><a target="_blank" href="/html/example-with-lp.phtml.txt">example-with-lp.phtml.txt</a> and <a target="_blank" href="/html/example-without-lp.phtml.txt">example-without-lp.phtml.txt</a> are the source code of the phtml pages.</p>

<p>On the top of the sample page not using LightningPacker you can see the CSS headers</p>

<div class="html">
<?php 
echo htmlentities('<head>
<title>Example of Page without LightningPacker</title>
<link rel="shortcut icon" href="/img/example/favicon.ico" type="image/x-icon" />
<link href="/css/810.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/example.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/example-simplemodal.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/jquery.jqzoom.css" media="screen" rel="stylesheet" type="text/css" />
</head>');
?>
</div>

<p>It will cause the browser to make four requests in order to understand the page's layout. The code snipet bellow belongs to the example using LightningPacker.</p>

<div class="html">
<?php

echo htmlentities('<head>
<title>Example of Page with LightningPacker</title>
<link rel="shortcut icon" href="/img/example/favicon.ico" type="image/x-icon" />
<?= lightningPacker(array("http://lightningpacker.net/css/810.css", "http://lightningpacker.net/css/example.css", "http://lightningpacker.net/css/example-simplemodal.css", "http://lightningpacker.net/css/jquery.jqzoom.css"), "css"); ?>;
</head>');
?>

</div>

<p>In terms of CSS, both approaches have the exactly same effect. The difference is the number of requests performed and the amount of data tranfered.</p>

