<p>This section contains and example of LightningPacker usage and a performance analisys on the difference between a page using LightningPacker and a page that dont.</p>

<p>The <a target="_blank" href="/html/example-with-lp.html">example-with-lp.html</a> contains an example using LightningPacker.</p>

<p>The page <a target="_blank" href="/html/example-without-lp.html">example-without-lp.html</a> is the very same page but instead of call LightningPacker the page is calling each separately</p>



