<h2>Project's Idea</h2>

<p><span class="highlight">LightningPacker is a sort of online Minify that you can plug in directly on your website</span>. Minify allow your pages to render with less requests. It concatenates scripts and then apply a bunch of optimizations to make the content have the smallest possible size. LightningPacker caches your scripts all together and make it available. It doesn't require any installation and it's easy to use.</p>

<p>LightningPacker handles both JS and CSS files. You provide a set of URLs and LightningPacker compress and cache it for later use. When a browser renders your page, instead of make multiple requests to your sever, it will make less requests and to LightningPacker.</p>

<p>Use LightningPacker gives two major benefits:</p>

<ul>
<li>Reduce the number of requests to the app's server;</li>
<li>Reduce load time;</li>
</ul>

<p>With less requests to your server you reduce the costs needed to keep your system running. With faster load time your users will have a better experience.</p>

<p> Go to <a href="/packagemanager">Pack Manager</a> to assemble your packages. The section <a href="/docs">Docs</a> have a full description of the API and a detailed description of how LightningPacker works, including a systematic way to create packages. <a href="/examples">Examples</a>, gives code snippets about using LightningPacker and a full example of how to use it.</p>

<h2>Help the Project</h2>

<p>If you are a developer, help me improve the project. Contact me at <a href="mailto:dmelo87@gmail.com">dmelo87@gmail.com</a>.</p>
