<h2>Project's Idea</h2>

<p>CDNs helps spreading requisitions across different locations while Minify make the browser perform fewer requests. LightningPacker gather the best from both ideas caching your scripts all together and making it available. Its doesn't require any installation and it's easy to use.</p>

<p>
LightningPacker handles js and css files. You provide a set of URLs and LightningPacker compress and cache it for later use. When a browser renders your page, instead of make multiple requests to your sever, it will make fewer requests and to LightningPacker. 
</p>

<p>There is two major benefits:</p>

<ul>
<li>Reduce amount of request to your server;</li>
<li>Reduce load time;</li>
</ul>

<p>With less requests to your server you reduce the costs needed to keep your system running. With faster load time your users will have a better experience on your site.</p>

<p> Go to <a href="/exemples">exemples</a> to see live examples of how to use LightningPacker. The section <a href="/docs">Docs</a> have a full description of the API and a detailed description of how LightningPacker works.</p>

<h2>Upcoming Features</h2>

<ul>
<li>Improve packit.php (the script responsable for all the magic);</li>
<li>Write code to make it easy to use with PHP and Zend Framework;</li>
<li>Build integrations between LightningPacker and other systems like: Drupal, Joomla, Magento</li>
<li>Build a Network of server geographically spreaded to improve time.</li>
</ul>

<h2>Help the Project</h2>

<p>If you are a developer, help me improve the project. Contact me at <a href="mailto:dmelo87@gmail.com">dmelo87@gmail.com</a>.</p>
