<p>CDNs helps spreading requisitions across different locations while Minify make the browser perform fewer requests. LightningPacker gather the best from both ideas caching your scripts all together and making it available. Its doesn't require any installation and is easy to use.</p>

<p>
Make it faster and lighter. LighteningPacker compress and distribute your js and css files over the internet. You provide a set of URLs and LighteningPacker compress and cache it for later use. When a browser renders your page, instead of make multiple requests to your sever, it will make fewwer requests and to LighteningPacker.
</p>
