<html>

<head>
<title>Example of Page without LightningPacker</title>
<link rel="shortcut icon" href="/img/example/favicon.ico" type="image/x-icon" />
<link href="/css/810.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/example.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/example-simplemodal.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/css/jquery.jqzoom.css" media="screen" rel="stylesheet" type="text/css" />
</head>

<body>

<div class="container container_3">
<div class="grid_3">

<h1>Example of Page without LightningPacker</h1>

<p>Click <a href="#" id="simplemodal">here</a> to see a simplemodal.</a>

<div id="div-simplemodal">
<div id="simplemodal-container">
<a class="modalCloseImg"></a>
<p>A very simple and yet nice modal</p>
<small>Press Esc to close the modal</small>
</div>
</div>

<p>Here goes a very nice zoom effect.</p>
<a href="/img/example/car.jpg" class="jqzoom">
<img src="/img/example/car-small.jpg"/>
</a>

<img style="display: none" src="/img/example/car.jpg"/>

</div>
</div>


<script type="text/javascript" src="http://code.jquery.com/jquery-1.6.2.min.js"></script>
<script type="text/javascript" src="http://simplemodal.googlecode.com/files/jquery.simplemodal-1.4.1.js"></script>
<script type="text/javascript" src="/js/jquery.jqzoom-core-pack.js"></script>
<script type="text/javascript" src="/js/example.js"></script>

</body>
</html>
